site_name: Scenariusze lekcji Informatyka
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - pymdownx.arithmatex:
      generic: true
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/preview-popup.js
  - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Strona główna: index.md
  - Scenariusze lekcji:
      - Lekcja 1 - Wprowadzenie: scenarios/lesson0.md
      - Lekcja 2 - Co to algorytm?: scenarios/lesson1.md
      - Lekcja 3 - Instrukcja warunkowa: scenarios/lesson2.md
      - Lekcja 4 - Pętle: scenarios/lesson3.md
      - Lekcja 5 - Projekt: scenarios/lesson4.md
      - Lekcja 6 - Funkcje: scenarios/lesson5.md