site_name: Scenariusze lekcji Informatyka
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - pymdownx.arithmatex:
      generic: true
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/preview-popup.js
  - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Strona główna: index.md
  - Scenariusze lekcji:
      - Lekcja 1 - Podstawy Pythona – pierwsze kroki. Po co programować?: scenarios/lesson0.md
      - Lekcja 2 - Algorytmy od kuchni i nie tylko. Podstawowe pojęcia, algorytm i jego specyfikacja.: scenarios/lesson1.md
      - Lekcja 3 - Instrukcje warunkowe – if, elif, else. Jak kierować zachowaniem komputera?: scenarios/lesson2.md
      - Lekcja 4 - Pętle for i while – iteracje, przerwania (break, continue). Jak sobie poradzić z powtarzalną pracą?: scenarios/lesson3.md
      - Lekcja 5 - Zastosowanie praktyczne. Quiz. Jak użyć tego co umiem?: scenarios/lesson4.md
      - Lekcja 6 - Funkcje w Pythonie – argumenty, wartości zwracane, funkcje wbudowane.: scenarios/lesson5.md
      - Lekcja 7 - Matematyka z pomocą Pythona – Jak napisać program rozwiązujący moją pracę domową?: scenarios/lesson6.md
      - Lekcja 8 - Lista, słowa – kiedy zmienna nie wystarcza.: scenarios/lesson7.md
      - Lekcja 9 - Zastosowanie praktyczne – Sterowanie „robotem”. Biblioteka turtle.: scenarios/lesson8.md